create table if not exists products (
    pro_cod bigint not null generated by default as identity,
    pro_name varchar not null,
    pro_price numeric not null,
    pro_available_stock integer not null,
    constraint products_pro_cod_pkey primary key (pro_cod)
);