create table if not exists product (
    pro_cod bigint not null generated by default as identity,
    pro_name varchar not null,
    pro_price numeric(12, 2) not null,
    pro_available_stock integer not null,

    constraint products_pro_cod_pkey primary key (pro_cod),
    constraint products_pro_name_ukey unique (pro_name),
    constraint products_pro_name_check check (pro_name <> ''),
    constraint products_pro_price_check check (pro_price >= 0),
    constraint products_pro_available_stock_check check (pro_available_stock >= 0)
);