create table if not exists products (
    id bigint not null generated by default as identity,
    name varchar not null,
    price numeric not null,
    available_stock integer not null,
    constraint product_id_pkey primary key (id)
);